name: aphrodite
description: "this app is amazing!"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  shared_preferences: ^2.0.8
  flutter_launcher_icons: ^0.9.2
  cupertino_icons: ^1.0.6
  provider: ^6.0.2
  image_picker: ^0.8.4

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
